### ISSUE TITLE
Update Community Profile?

### ISSUE THREAD

**Issue by thedogbup** [dj-pixus/lmms-collab#11]
If we fill out the community info from Insights -> Community, we might attract more people to this project. Also, I think the readme stuff fits better there.

**Comment by dj-pixus** [comment]
Absolutely! But now that I think about it, there are some points in the readme that are not even valid anymore. For example it says not to use any external resources, but it can work with relative paths, right? So we need to refine the rules a bit to actually make people want to join, but yes it's a good idea to make some order.
Also, let's just get rid of that archive folder completely as it doesn't make any sense.

p.s. "Black Magic", seriously? :D

**Comment by thedogbup** [comment]
Lol
I'm not exactly sure how relative paths work with LMMS yet but I'm sure we'll figure something out. I don't feel an urgent need to include anything outside yet; if we manage to stay with the stock plugins and samples, we could even upload the finished project on LSP and maybe (fingers crossed) have it included as a demo.

If you feel like we're done with the community tab, you can close the issue

**Comment by dj-pixus** [comment]
Well relative paths are not officially supported by LMMS, but you can manually edit paths in the project file so it will work. But it's still unlikely that this will be needed as LMMS's stock plugins can do really decent job. I mean, I've never felt need for any external plugins for any of my music, ever.
Then there is licensing wich would be rather difficult to oversee at the moment. In a project like this CC0 is clearly the only way to go, so i'm gonna just use that nice license template that Github offers and also mention it the readme.

**Comment by thedogbup** [comment]
I mean, once you start using external plugins, it's hard to go back lol
