### ISSUE TITLE
More plugin importing issues

### ISSUE THREAD

**Issue by thedogbup** [dj-pixus/lmms-collab#6]
* Issues with ``noclue``:
  * ![image](https://user-images.githubusercontent.com/50534745/88582916-798af400-d01d-11ea-88a0-3ddc242f753a.png)

* Issues with ``ox7curse``:
  * ![image](https://user-images.githubusercontent.com/50534745/88582570-eea9f980-d01c-11ea-8677-337f471d8780.png)
  * ![image](https://user-images.githubusercontent.com/50534745/88582613-01243300-d01d-11ea-96ee-e28b5ff16d95.png)

* Issue with ``ox7style``:
  * Opulenz does not import properly either

Can you check if these work for anyone else? It's possible it's just on my end.

**Comment by dj-pixus** [comment]
OpulenZ works strange for me too, but only if the project was made with an older version. It has something to do with the OPL2 being renamed to actually OpulenZ. I compiled the master branch, so maybe that is the issue.
About the LADSPA plugins: Readme.md !
